### ISSUE TITLE
Fixed value 183891

### ISSUE THREAD

**Issue by valkiii** [ibrahimsharaf/doc2vec#1]
Hi, it is not clear for me why in the getVecs function,  
`if(vecs_type == 'Test'):
    index = index + 183891`
Is there any reason to put that value?

**Comment by ibrahimsharaf** [comment]
Hi @valkiii, thank you for opening the issue.

Actually this was a hard-coded value, which referred to the length of training data, I pushed a new commit to fix it.

Thanks!
