### ISSUE TITLE
Softwares needed

### ISSUE THREAD

**Issue by mannamh** [ibrahimsharaf/doc2vec#2]
Hi Ibrahim,

I have been using Scala/Spark for text analysis. I am in the process of switching over to Python as many new algorithms are available in Python. I am trying your doc2vec example mentioned here and able to understand the code.  But When I run "python model.py", I was keep on getting basic errors like 'Import error: module not found' etc. I understood that I am missing some of the python modules. It would be very beneficial if you can update the code with 'Usage' as in the packages needed to run this code. For example, does this code needs python3/python? I really appreciate your response. Thanks for your help and time.

**Comment by ibrahimsharaf** [comment]
Hi @mannamh, thank you for opening the issue.
I updated the repo now, you can check the README for usage instructions.

**Comment by mannamh** [comment]
Thanks for your time Ibrahim. This helps.
